authentication/urls.py
from authentication.views import EmailValidationView, RegistrationView, UsernameValidationView,VerificationView, LoginView,LogoutView,profile
from django.urls import path
from django.views.decorators.csrf import csrf_protect,csrf_exempt
from django.contrib.auth import views as auth_views
from django.conf.urls import include
from django.urls import reverse_lazy

app_name = "authentication"
urlpatterns= [
    path('register/',(RegistrationView.as_view()), name="register"),
    path('login/',(LoginView.as_view()), name="login"),
    path('logout/',(LogoutView.as_view()), name="logout"),
    path('validate-username/',csrf_exempt(UsernameValidationView.as_view()),name="validate-username"),
    path('validate-email/',csrf_exempt(EmailValidationView.as_view()), name="validate-email"),
    path('activate/<uidb64>/<token>',
         VerificationView.as_view(), name='activate'),
    path("profile/",profile,name="profile"),
    
]

kportal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor/",include("ckeditor_uploader.urls")),
    path("",include("expenses.urls")),
     path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='authentication/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='authentication/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='authentication/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='authentication/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path("authentication/",include('authentication.urls')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

authentication/views.py
from django.shortcuts import render, redirect
from django.views import View
import json
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.contrib.auth.models import User
from validate_email import validate_email
from django.contrib import messages
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text, DjangoUnicodeDecodeError
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.template.loader import render_to_string
from authentication.utils.utils import account_activation_token
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from authentication.forms import UserUpdateForm, UserRegisterForm, ProfileUpdateForm
from authentication.models import Profile


class EmailValidationView(View):
    def post(self, request):
        data = json.loads(request.body)
        email = data['email']
        if not validate_email(email):
            return JsonResponse({'email_error': 'Email is invalid'}, status=400)
        if User.objects.filter(email=email).exists():
            return JsonResponse({'email_error': 'sorry email in use,choose another one '}, status=409)
        return JsonResponse({'email_valid': True})


class UsernameValidationView(View):
    def post(self, request):
        data = json.loads(request.body)
        username = data['username']
        if not str(username).isalnum():
            return JsonResponse({'username_error': 'username should only contain alphanumeric characters'}, status=400)
        if User.objects.filter(username=username).exists():
            return JsonResponse({'username_error': 'sorry username in use,choose another one '}, status=409)
        return JsonResponse({'username_valid': True})


class RegistrationView(View):
    def get(self, request):
        return render(request, 'authentication/register.html')

    def post(self, request):
        # GET USER DATA
        # VALIDATE
        # create a user account

        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        context = {
            'fieldValues': request.POST
        }

        if not User.objects.filter(username=username).exists():
            if not User.objects.filter(email=email).exists():
                if len(password) < 6:
                    messages.error(request, 'Password too short')
                    return render(request, 'authentication/register.html', context)

                user = User.objects.create_user(username=username, email=email)
                user.set_password(password)
                user.is_active = False
                user.save()
                current_site = get_current_site(request)
                email_body = {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                }

                link = reverse('activate', kwargs={
                               'uidb64': email_body['uid'], 'token': email_body['token']})

                email_subject = 'Activate your account'

                activate_url = 'http://'+current_site.domain+link

                email = EmailMessage(
                    email_subject,
                    'Hi '+user.username + ', Please the link below to activate your account \n'+activate_url,
                    'noreply@semycolon.com',
                    [email],
                )
                email.send(fail_silently=False)
                messages.success(request, 'Account successfully created')
                return render(request, 'authentication/register.html')

        return render(request, 'authentication/register.html')


class VerificationView(View):
    def get(self, request, uidb64, token):
        try:
            id = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=id)

            if not account_activation_token.check_token(user, token):
                return redirect('login'+'?message='+'User already activated')

            if user.is_active:
                return redirect('authentication:login')
            user.is_active = True
            user.save()

            messages.success(request, 'Account activated successfully')
            return redirect('authentication:login')

        except Exception as ex:
            pass

        return redirect('authentication:login')


class LoginView(View):
    def get(self, request):
        return render(request, 'authentication/login.html')

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']

        if username and password:
            user = auth.authenticate(username=username, password=password)

            if user:
                if user.is_active:
                    auth.login(request, user)
                    messages.success(request, 'Welcome, ' +
                                     user.username+' you are now logged in')
                    return redirect('expenses:homepage')
                messages.error(
                    request, 'Account is not active,please check your email')
                return render(request, 'authentication/login.html')
            messages.error(
                request, 'Invalid credentials,try again')
            return render(request, 'authentication/login.html')

        messages.error(
            request, 'Please fill all fields')
        return render(request, 'authentication/login.html')


class LogoutView(View):
    def post(self, request):
        auth.logout(request)
        messages.success(request, 'You have been logged out')
        return redirect('authentication:login')


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('authentication:profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'authentication/profile.html', context)

kportal/templates/authentication/_base_auth.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>KPortal  {% block title %}
    {% endblock %}   </title>
    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
<link href="{% static 'css/main.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
  </head>
  <body>

    <main role="main">



      {% block content %}

      {% endblock %}


    </main>
  </div>
</div>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f" crossorigin="anonymous"></script>
    <script
    src="{% static 'js/bootstrap.bundle.min.js' %}"
  ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
     <script src="{% static 'js/main.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
        <script src="{% static 'js/main.js' %}"></script></body>
</html>

kportal/templates/authentication/login.html
{% extends 'authentication/_base_auth.html' %}
{% load static %}


{% block content %}

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class="card mt-5">


      <div class="card-body">
        <div class="card-title py-3">
          <h4>Login to your  account</h4>
        </div>
        <form action="{% url 'authentication:login' %}" method="post">
          {% csrf_token %}

          {% include 'messages/auth_messages.html' %}
          <div class="form-group">
            <input
              type="text"
              name="username"
              placeholder="username"
              id="usernameField"
              value="{{fieldValues.username}}"
              class="form-control form-control-sm"
            />
          </div>
          <div class="form-group">
            <input
              type="password"
              name="password"
              placeholder="Password"
              class="form-control form-control-sm"
              id="passwordField"
            />
          </div>
          <input type="submit" value="Login" class="btn btn-block btn-primary submit-btn" />
        </form>
<p class="text-muted ml-2">Don't Have an account !!! <a href="{% url 'authentication:register'%}">SignUp Here</a></p>

<p class="text-muted ml-2">
  <a href="{% url 'password_reset' %}">Forgot Password?</a>
</p>
      </div>

      </div>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>

<script src="{% static 'js/register.js' %}"></script>

{% endblock content %}

kportal/templates/authentication/password_reset.html
{% extends "authentication/_base_auth.html" %}
{% block content %}

    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <div class="card mt-5">
      
      
            <div class="card-body">
              <div class="card-title py-3">
                <h4>Reset Password</h4>
              </div>
              <form method="post">
                {% csrf_token %}
      
                {% include 'messages/auth_messages.html' %}
                {{form}}
                
                <input type="submit" value="Login" class="mt-2 btn btn-block btn-primary submit-btn" />
              </form>
            </div>
      
            </div>
          </div>
        </div>
        <div class="col-md-4"></div>
      </div>
      
    <style>
        input{
            width: 100%;
        }
    </style>
{% endblock content %}

kportal/templates/authentication/password_reset_complete.html
{% extends "authentication/_base_auth.html" %}
{% block content %}
    

    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <div class="card mt-5">
      
      
            <div class="card-body">
              <div class="card-title py-3">
                <h4> Your password has been set.</h4>
              </div>
              <a href="{% url 'authentication:login' %}">Sign In Here</a>
            </div>
      
            </div>
          </div>
        </div>
        <div class="col-md-4"></div>
      </div>
      
    <style>
        input{
            width: 100%;
        }
    </style>
{% endblock content %}

kportal/templates/authentication/password_reset_confirm.html
{% extends "authentication/_base_auth.html" %}
{% block content %}


    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <div class="card mt-5">
      
      
            <div class="card-body" style="background-color: rgb(222, 242, 247);">
              <div class="card-title py-3">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Reset Password</legend>
                        {{ form}}
                    </fieldset>
                    
                    <input type="submit" value="Reset Password" class="mt-2 btn btn-block btn-primary submit-btn" />
                </form>
            </div>
      
            </div>
          </div>
        </div>
        <div class="col-md-4"></div>
      </div>
      
    <style>
        input{
            width: 100%;
        }
    </style>
{% endblock content %}

kportal/templates/authentication/password_reset_done.html
{% extends "authentication/_base_auth.html" %}
{% block content %}
    

    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <div class="card mt-5">
      
      
            <div class="card-body" style="background-color: rgb(222, 242, 247);">
              <div class="card-title py-3">
               <h1>An email has been sent with instructions to reset your password</h1> 
            </div>
      
            </div>
          </div>
        </div>
        <div class="col-md-4"></div>
      </div>
      
    <style>
        input{
            width: 100%;
        }
    </style>
{% endblock content %}

kportal/templates/authentication/profile.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
{% include 'messages/auth_messages.html'%}
<!-- <div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
    <div class="media-body">
      <h2 class="account-heading">{{ user.username }}</h2>
      <p class="text-secondary">{{ user.email }}</p>
    </div>
  </div>
  <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4">Profile Info</legend>
          {{ u_form}}
          {{ p_form}}
      </fieldset>
      <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Update</button>
      </div>
  </form>
</div> -->

  <div class="container">
    <div class="col-left">
      <div class="login-text">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
      <h2 class="account-heading">{{ user.username }}</h2>
      <p class="text-secondary">{{ user.email }}</p>
        
        
      </div>
    </div>
    <div class="col-right">
      <div class="login-form">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Update Profile Info</legend>
              {{ u_form}}
              {{ p_form}}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form>
      </div>
    </div>
  </div>

<style>
  /* * * * * General CSS * * * * */
*,
*::before,
*::after {
  box-sizing: border-box;
}


.wrapper {
  margin: 0 auto;
  width: 100%;
  max-width: 1140px;
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
}

.container {
  position: relative;
  width: 100%;
  max-width: 600px;
  height: auto;
  display: flex;
  background: #ffffff;
  box-shadow: 0 0 15px rgba(0, 0, 0, .1);
}

.credit {
  position: relative;
  margin: 15px auto 0 auto;
  width: 100%;
  text-align: center;
  color: #666666;
  font-size: 16px;
  font-weight: 400;
}

.credit a {
  color: #222222;
  font-size: 16px;
  font-weight: 600;
}

/* * * * * Login Form CSS * * * * */
h2 {
  margin: 0 0 15px 0;
  font-size: 30px;
  font-weight: 700;
}

h2 img {
  width: 100px;
}

p {
  margin: 0 0 20px 0;
  font-size: 16px;
  font-weight: 500;
  line-height: 22px;
}

.btn {
  display: inline-block;
  padding: 7px 20px;
  font-size: 16px;
  letter-spacing: 1px;
  text-decoration: none;
  border-radius: 5px;
  color: #0af846;
  outline: none;
  border: 1px solid #16e716;
  transition: .3s;
  -webkit-transition: .3s;
}

.btn:hover {
  color: #4CAF50;
  background: #ffffff;
}

.col-left,
.col-right {
  width: 55%;
  padding: 45px 35px;
  display: flex;
}

.col-left {
  width: 45%;
  background: #4CAF50;
  -webkit-clip-path: polygon(98% 17%, 100% 34%, 98% 51%, 100% 68%, 98% 84%, 100% 100%, 0 100%, 0 0, 100% 0);
  clip-path: polygon(98% 17%, 100% 34%, 98% 51%, 100% 68%, 98% 84%, 100% 100%, 0 100%, 0 0, 100% 0);
}

@media(max-width: 575.98px) {
  .container {
    flex-direction: column;
    box-shadow: none;
  }

  .col-left,
  .col-right {
    width: 100%;
    margin: 0;
    padding: 30px;
    -webkit-clip-path: none;
    clip-path: none;
  }
}

.login-text {
  position: relative;
  width: 100%;
  color: #ffffff;
  text-align: center;
}

.login-form {
  position: relative;
  width: 100%;
  color: #666666;
}

.login-form p:last-child {
  margin: 0;
}

.login-form p a {
  color: #4CAF50;
  font-size: 14px;
  text-decoration: none;
}

.login-form p:last-child a:last-child {
  float: right;
}

.login-form label {
  display: block;
  width: 100%;
  margin-bottom: 2px;
  letter-spacing: .5px;
}

.login-form p:last-child label {
  width: 60%;
  float: left;
}

.login-form label span {
  color: #ff574e;
  padding-left: 2px;
}

.login-form input {
  display: block;
  width: 100%;
  height: 40px;
  padding: 0 10px;
  font-size: 16px;
  letter-spacing: 1px;
  outline: none;
  border: 1px solid #cccccc;
  border-radius: 5px;
}

.login-form input:focus {
  border-color: #ff574e;
}

.login-form input.btn {
  color: #ffffff;
  background: #4CAF50;
  border-color: #4CAF50;
  outline: none;
  cursor: pointer;
}

.login-form input.btn:hover {
  color: #4CAF50;
  background: #ffffff;
}
</style>
{% endblock %}

kportal/templates/authentication/register.html
{% extends 'authentication/_base_auth.html' %}
{% load static %}


{% block content %}

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class="card mt-5">


      <div class="card-body">
        <div class="card-title py-3">
          <h4>Register for a free account</h4>
        </div>
        {% include "messages/auth_messages.html"%}
        <form action="{% url 'authentication:register' %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <input
              type="text"
              name="username"
              placeholder="username"
              id="usernameField"
              value="{{fieldValues.username}}"
              class="form-control form-control-sm"
            />
          </div>
          <div class="invalid_feedback invalid-feedback" style="display:none">
          </div>
          <p class="text-sm text-success usernameSuccessOutput"></p>
          <div class="form-group">
            <input
              type="email"
              name="email"
              placeholder="Email"
              class="form-control form-control-sm"
              id="emailField"

              value="{{fieldValues.email}}"
            />
          </div>

          <div class="emailFeedBackArea invalid-feedback" style="display:none">
          </div>
          <div class="form-group">
            <input
              type="password"
              name="password"
              placeholder="Password"
              class="form-control form-control-sm"
              id="passwordField"
            />
            <small class="float-right py-3 showPasswordToggle">SHOW</small>
          </div>
          <input type="submit" value="Register" class="btn btn-block btn-primary submit-btn" />
        </form>
        <p> Have an account !!! <a href="{% url 'authentication:login'%}">Login Here</a></p>

      </div>

      </div>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>

<script src="{% static 'js/register.js' %}"></script>

{% endblock content %}

kportal/templates/authentication/reset_pass.html
{% extends 'authentication/_base_auth.html'%}

{% block content%}
   <div class="card">
       <div class="card-body">
           <h1>RESET</h1>
       </div>
   </div>
{% endblock %}

kportal/templates/authentication/set_new_password.html
{% extends 'authentication/_base_auth.html'%}

{% block content%}
   <div class="card">
       <div class="card-body">
           <h1>SET NEW PASSWORD</h1>
       </div>
   </div>
{% endblock %}