authentication/urls.py
from authentication.views import EmailValidationView, RegistrationView, UsernameValidationView,VerificationView, LoginView,LogoutView,profile
from django.urls import path
from django.views.decorators.csrf import csrf_protect,csrf_exempt
from django.contrib.auth import views as auth_views
from django.conf.urls import include
from django.urls import reverse_lazy

app_name = "authentication"
urlpatterns= [
    path('register/',(RegistrationView.as_view()), name="register"),
    path('login/',(LoginView.as_view()), name="login"),
    path('logout/',(LogoutView.as_view()), name="logout"),
    path('validate-username/',csrf_exempt(UsernameValidationView.as_view()),name="validate-username"),
    path('validate-email/',csrf_exempt(EmailValidationView.as_view()), name="validate-email"),
    path('activate/<uidb64>/<token>',
         VerificationView.as_view(), name='activate'),
    path("profile/",profile,name="profile"),
    
]

expenses/urls.py
from django.urls import path
from expenses import views

app_name = "expenses"
urlpatterns = [
    path("",views.homepage,name="homepage")
]

kportal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor/",include("ckeditor_uploader.urls")),
    path("",include("expenses.urls")),
     path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='authentication/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='authentication/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='authentication/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='authentication/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path("authentication/",include('authentication.urls')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

kportal/templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>KPortal {% block title %} {% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet" />
    <link href="{% static 'css/main.css'%}" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet" />
  </head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'expenses:homepage'%}">KPortal</a>

      <ul
        class="navbar-nav px-3"
        style="display: flex; flex-direction: row; align-items: center;"
      >
        <li class="nav-item text-nowrap">
          <span class="nav-link"><a href="{% url 'authentication:profile'%}">({{request.user.username}})</a>
          </span>
        </li>
        
        <li class="nav-item text-nowrap mt-3 ml-2">
          <form action="{% url  'authentication:logout' %}" method="POST">
            {% csrf_token %}
            <input
              class="text text-capitalize"
              type="submit"
              value="Sign out"
            />
          </form>
        </li>
      </ul>
    </nav>

    

        <main role="main" class="col-md-12 mt-5">
          {% block content %} {% endblock %}
        </main>
      
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script>
      window.jQuery ||
        document.write(
          '<script src="/docs/4.4/static/js/vendor/jquery.slim.min.js"><\/script>'
        );
    </script>
    <script
      src="{% static 'js/bootstrap.bundle.min.js' %}"
      integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
     <script src="{% static 'js/main.js' %}"></script>
     <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js'%}"></script>
     <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js'%}"></script>
  </body>
</html>